apiVersion: v1
kind: Service
metadata:
  name: tweetappapi-service
spec:
  selector:
    app: tweetappapi-pod
  ports:
  - port: 8081
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: tweetappapi-ingress
spec:
    rules:
    - http:
        paths:
        - path: /mongodbapi
          pathType: Prefix
          backend:
            service:
              name: tweetappapi-service
              port:
                number: 80
--- 
